{
 "title": "3PL Delivery Partner - API",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Total 3PL API Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  increase(\r\n    http_request_duration_seconds_count{\r\n      job=\"main-api\",\r\n      path=~\".*(buyer-service|api-gateway|3pl-provider-3|sample\\\\.io|3pl-provider-8|3pl-provider-2|sample\\\\.in|3pl-provider-6|3pl-provider-7|now\\\\.sample|routing-service|sample\\\\.delivery|picoxpress|porter|3pl-provider-10|3pl-provider-4\\\\.sample|3pl-provider-1|3pl-provider-5|sample\\\\.sample\\\\.sample|3pl-provider-14).*\"\r\n    }[$__range]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Average 3PL API Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(\r\n    http_request_duration_seconds_sum{\r\n      job=\"main-api\",\r\n      path=~\".*(buyer-service|api-gateway|3pl-provider-3|sample\\\\.io|3pl-provider-8|3pl-provider-2|sample\\\\.in|3pl-provider-6|3pl-provider-7|now\\\\.sample|routing-service|sample\\\\.delivery|picoxpress|porter|3pl-provider-10|3pl-provider-4\\\\.sample|3pl-provider-1|3pl-provider-5|sample\\\\.sample\\\\.sample|3pl-provider-14).*\"\r\n    }[$__range]\r\n  )\r\n)\r\n/\r\nsum(\r\n  rate(\r\n    http_request_duration_seconds_count{\r\n      job=\"main-api\",\r\n      path=~\".*(buyer-service|api-gateway|3pl-provider-3|sample\\\\.io|3pl-provider-8|3pl-provider-2|sample\\\\.in|3pl-provider-6|3pl-provider-7|now\\\\.sample|routing-service|sample\\\\.delivery|picoxpress|porter|3pl-provider-10|3pl-provider-4\\\\.sample|3pl-provider-1|3pl-provider-5|sample\\\\.sample\\\\.sample|3pl-provider-14).*\"\r\n    }[15m]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "3PL Traffic Share",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (path) (\r\n  rate(\r\n    http_request_duration_seconds_count{\r\n      job=\"main-api\",\r\n      path=~\".*(external-service|api-gateway|3pl-provider-5|sample\\\\.sample\\\\.sample|routing-service|3pl-provider-3|buyer-service|sample\\\\.io|picoxpress|3pl-provider-14|3pl-provider-6|sample\\\\.in|3pl-provider-10|sample\\\\.delivery|now\\\\.sample|3pl-provider-2|3pl-provider-4\\\\.sample|api\\\\.3pl-provider-8\\\\.in|porter|3pl-provider-7).*\"\r\n    }[$__range]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall 3PL Traffic Trend",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(\r\n    http_request_duration_seconds_count{\r\n      job=\"main-api\",\r\n      path=~\".*(buyer-service|api-gateway|3pl-provider-3|sample\\\\.io|3pl-provider-8|3pl-provider-2|sample\\\\.in|3pl-provider-6|3pl-provider-7|now\\\\.sample|routing-service|sample\\\\.delivery|picoxpress|porter|3pl-provider-10|3pl-provider-4\\\\.sample|3pl-provider-1|3pl-provider-5|sample\\\\.sample\\\\.sample|3pl-provider-14).*\"\r\n    }[$__range]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Overall Server Error Rate (5xx %)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(http_request_duration_seconds_count{\r\n    job=\"main-api\",path=~\".*(buyer-service|api-gateway|3pl-provider-3|sample\\\\.io|3pl-provider-8|3pl-provider-2|sample\\\\.in|3pl-provider-6|3pl-provider-7|now\\\\.sample|routing-service|sample\\\\.delivery|picoxpress|porter|3pl-provider-10|3pl-provider-4\\\\.sample|3pl-provider-1|3pl-provider-5|sample\\\\.sample\\\\.sample|3pl-provider-14).*\",\r\n    status_code=~\"5..\"\r\n  }[$__range]))\r\n/\r\n  sum(rate(http_request_duration_seconds_count{\r\n    job=\"main-api\", path=~\".*(buyer-service|api-gateway|3pl-provider-3|sample\\\\.io|3pl-provider-8|3pl-provider-2|sample\\\\.in|3pl-provider-6|3pl-provider-7|now\\\\.sample|routing-service|sample\\\\.delivery|picoxpress|porter|3pl-provider-10|3pl-provider-4\\\\.sample|3pl-provider-1|3pl-provider-5|sample\\\\.sample\\\\.sample|3pl-provider-14).*\",\r\n  }[$__range]))\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 Busiest APIs",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\r\n  5,\r\n  sum by (path) (\r\n    increase(\r\n      http_request_duration_seconds_count{\r\n        job=\"main-api\",\r\n        path=~\".*(buyer-service|api-gateway|3pl-provider-3|sample\\\\.io|3pl-provider-8|3pl-provider-2|sample\\\\.in|3pl-provider-6|3pl-provider-7|now\\\\.sample|routing-service|sample\\\\.delivery|picoxpress|porter|3pl-provider-10|3pl-provider-4\\\\.sample|3pl-provider-1|3pl-provider-5|sample\\\\.sample\\\\.sample|3pl-provider-14).*\"\r\n      }[$__range]\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 Slowest APIs",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\r\n  5,\r\n  histogram_quantile(\r\n    0.95,\r\n    sum by (le, path) (\r\n      rate(\r\n        http_request_duration_seconds_bucket{\r\n          job=\"main-api\",\r\n          path=~\".*(buyer-service|api-gateway|3pl-provider-3|sample\\\\.io|3pl-provider-8|3pl-provider-2|sample\\\\.in|3pl-provider-6|3pl-provider-7|now\\\\.sample|routing-service|sample\\\\.delivery|picoxpress|porter|3pl-provider-10|3pl-provider-4\\\\.sample|3pl-provider-1|3pl-provider-5|sample\\\\.sample\\\\.sample|3pl-provider-14).*\"\r\n        }[$__range]\r\n      )\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P99",
   "type": "text",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "options": {
    "content": "--Shows the response time for the slowest 1% of requests.\r\n\r\n--99% of users are faster, only 1% face extreme slowness.\r\n\r\n--Highlights rare but critical issues.\r\n\r\n--Used for SLA/SLO and alerting."
   }
  },
  {
   "title": "P95",
   "type": "text",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "options": {
    "content": "--Shows the slowest 5% requests\r\n\r\n--95% users get faster responses\r\n\r\n--Indicates system stability under load\r\n\r\n--Used for reliability monitoring"
   }
  },
  {
   "title": "P50",
   "type": "text",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "options": {
    "content": "--Shows the middle response time\r\n\r\n--50% requests are faster, 50% are slower\r\n\r\n--Represents normal user experience\r\n\r\n--Used to check average performance"
   }
  },
  {
   "title": "Shiprocket API Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*apiv2\\\\.3pl-provider-1\\\\.in/v1/external/.*\"\r\n      }[15m]),\r\n\r\n      \"endpoint\",\r\n      \"/$1\",\r\n\r\n      \"path\",\r\n      \".*apiv2\\\\.3pl-provider-1\\\\.in/v1/external/(.+)$\"\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shiprocket API Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*apiv2\\\\.3pl-provider-1\\\\.in/v1/external/.*\"\r\n      }[15m]),\r\n\r\n      \"endpoint\",\r\n      \"/$1\",\r\n\r\n      \"path\",\r\n      \".*apiv2\\\\.3pl-provider-1\\\\.in/v1/external/(.+)$\"\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shiprocket API Latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.50,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*apiv2\\\\.3pl-provider-1\\\\.in/v1/external/.*\"\r\n      }[15m]),\r\n\r\n      \"endpoint\",\r\n      \"/$1\",\r\n\r\n      \"path\",\r\n      \".*apiv2\\\\.3pl-provider-1\\\\.in/v1/external/(.+)$\"\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shadowfax API Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*(flash-api|api)\\\\.3pl-provider-2\\\\.in/.*\"\r\n      }[15m]),\r\n\r\n      \"endpoint\",\r\n      \"/$1\",\r\n\r\n      \"path\",\r\n      \".*(?:flash-api|api)\\\\.3pl-provider-2\\\\.in/(.+)$\"\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shadowfax API Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*(flash-api|api)\\\\.3pl-provider-2\\\\.in/.*\"\r\n      }[15m]),\r\n\r\n      \"endpoint\",\r\n      \"/$1\",\r\n\r\n      \"path\",\r\n      \".*(?:flash-api|api)\\\\.3pl-provider-2\\\\.in/(.+)$\"\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shadowfax API Latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.50,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*(flash-api|api)\\\\.3pl-provider-2\\\\.in/.*\"\r\n      }[15m]),\r\n\r\n      \"endpoint\",\r\n      \"/$1\",\r\n\r\n      \"path\",\r\n      \".*(?:flash-api|api)\\\\.3pl-provider-2\\\\.in/(.+)$\"\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ONDC API Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*buyer-service\\\\.XXX\\\\.com/opinteg/order/.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/opinteg/order/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ONDC API Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*buyer-service\\\\.XXX\\\\.com/opinteg/order/.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/opinteg/order/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ONDC API Latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.5,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*buyer-service\\\\.XXX\\\\.com/opinteg/order/.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/opinteg/order/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OLA API Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*routing-service.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/partner/order/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OLA API Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*routing-service.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/partner/order/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OLA API Latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.5,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*routing-service.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/partner/order/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rapido API Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*3pl-provider-4\\\\.sample.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/delivery/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rapido API Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*3pl-provider-4\\\\.sample.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/delivery/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rapido API Latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.5,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*3pl-provider-4\\\\.sample.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/delivery/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Qwqer API Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*api\\\\.3pl-provider-10\\\\.in/v2/.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*api\\\\.3pl-provider-10\\\\.in/v2/(.+)$\"\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Qwqer API Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*api\\\\.3pl-provider-10\\\\.in/v2/.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*api\\\\.3pl-provider-10\\\\.in/v2/(.+)$\"\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Qwqer API Latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.50,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*api\\\\.3pl-provider-10\\\\.in/v2/.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*api\\\\.3pl-provider-10\\\\.in/v2/(.+)$\"\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blitz API Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*api-gateway.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/v1/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blitz API Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*api-gateway.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/v1/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blitz API Latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.5,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*api-gateway.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/v1/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loadshare API Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*3pl-provider-6\\\\.net.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loadshare API Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*3pl-provider-6\\\\.net.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loadshare API Latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.50,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*3pl-provider-6\\\\.net.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delhivery API Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*sample\\\\.io.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/shipper/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delhivery API Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*sample\\\\.io.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/shipper/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delhivery API Latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.5,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*sample\\\\.io.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/shipper/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Telyport API Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*3pl-provider-5.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/v2/m/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Telyport API Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*3pl-provider-5.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/v2/m/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Telyport API Latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.5,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*3pl-provider-5.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/v2/m/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Yumove API Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*sample\\\\.sample\\\\.sample.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/api/v1/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Yumove API Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*sample\\\\.sample\\\\.sample.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/api/v1/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Yumove API Latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.5,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*sample\\\\.sample\\\\.sample.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/api/v1/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Borzo API Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*/3pl-provider-3\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/update\",\r\n      \"path\",\r\n      \".*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Borzo API Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*/3pl-provider-3\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/update\",\r\n      \"path\",\r\n      \".*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Borzo API Latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.5,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*/3pl-provider-3\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/update\",\r\n      \"path\",\r\n      \".*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Porter API Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*porter\\\\.in.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/([^/]+/[^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Porter API Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*porter\\\\.in.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/([^/]+/[^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Porter API Latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.5,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*porter\\\\.in.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/([^/]+/[^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dunzo API Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*api\\\\.3pl-provider-8\\\\.in.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"3pl-provider-8/$1\",\r\n      \"path\",\r\n      \".*/api/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dunzo API Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*api\\\\.3pl-provider-8\\\\.in.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"3pl-provider-8/$1\",\r\n      \"path\",\r\n      \".*/api/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dunzo API Latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.5,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*api\\\\.3pl-provider-8\\\\.in.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"3pl-provider-8/$1\",\r\n      \"path\",\r\n      \".*/api/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Magicpin API Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*3pl-provider-7.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/delivery/partner/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Magicpin API Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*3pl-provider-7.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/delivery/partner/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Magicpin API Latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.5,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*3pl-provider-7.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"/$1\",\r\n      \"path\",\r\n      \".*/delivery/partner/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pico API Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*picoxpress\\\\.com.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"pico/$1\",\r\n      \"path\",\r\n      \".*/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pico API Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*picoxpress\\\\.com.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"pico/$1\",\r\n      \"path\",\r\n      \".*/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pico API Latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.5,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*picoxpress\\\\.com.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"pico/$1\",\r\n      \"path\",\r\n      \".*/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sample API Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*sample\\\\.in.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"sample/$1\",\r\n      \"path\",\r\n      \".*/clientapi/v2/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sample API Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*sample\\\\.in.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"sample/$1\",\r\n      \"path\",\r\n      \".*/clientapi/v2/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sample API Latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.5,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*sample\\\\.in.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"sample/$1\",\r\n      \"path\",\r\n      \".*/clientapi/v2/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Opoli API Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*sample\\\\.delivery.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"opoli/$1\",\r\n      \"path\",\r\n      \".*/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Opoli API Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*sample\\\\.delivery.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"opoli/$1\",\r\n      \"path\",\r\n      \".*/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Opoli API Latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.5,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*sample\\\\.delivery.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"opoli/$1\",\r\n      \"path\",\r\n      \".*/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NowDelivery API Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*now\\\\.sample.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"nowdelivery/$1\",\r\n      \"path\",\r\n      \".*/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NowDelivery API Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*now\\\\.sample.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"nowdelivery/$1\",\r\n      \"path\",\r\n      \".*/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NowDelivery API Latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.5,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*now\\\\.sample.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"nowdelivery/$1\",\r\n      \"path\",\r\n      \".*/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zypp API Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*3pl-provider-14\\\\.com.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"zypp/$1\",\r\n      \"path\",\r\n      \".*/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zypp API Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*3pl-provider-14\\\\.com.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"zypp/$1\",\r\n      \"path\",\r\n      \".*/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zypp API Latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.5,\r\n  sum by (le, endpoint) (\r\n    label_replace(\r\n      rate(http_request_duration_seconds_bucket{\r\n        job=\"main-api\",\r\n        path=~\".*3pl-provider-14\\\\.com.*\"\r\n      }[15m]),\r\n      \"endpoint\",\r\n      \"zypp/$1\",\r\n      \"path\",\r\n      \".*/([^/]+).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}